apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mahmoudabohelwa3474/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_URI
          value: "mongodb://mongo:27017/mydatabase"

